defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

paginate: 10
paginate_path: "/blog/page:num/"

title: Christian Ezeani
subtitle: Full-Stack Developer

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Christian Ezeani"

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: fas fa-project-diagram

  - text: Skills & Offers
    link: /skills-and-offers
    icon: fas fa-chalkboard-teacher

  - text: Contact Me
    link: /contact
    icon: fas fa-portrait

  - text: My Resume
    link: /resume
    icon: fas fa-id-card

  - text: Blog Posts
    link: /blog
    icon: fas fa-pen

# Socialmedia Icons
social_icons:
  - name: linkedin
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter

  - name: linkedin2
    link: https://www.linkedin.com/christianezeani
    icon: fab fa-linkedin

  - name: github2
    link: https://github.com/christianezeani
    icon: fab fa-github-square

  - name: facebook2
    link: https://www.facebook.com/christian.ezeani.cyb
    icon: fab fa-facebook-square

  - name: twitter2
    link: https://www.twitter.com/christianezeani
    icon: fab fa-twitter
